default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  development:
    <<: *default
    database: rails101_development

  test:
    <<: *default
    database: rails101_test

  production:
    <<: *default
    database: rails101_production
    username: rails101
    password: <%= ENV['RAILS101_DATABASE_PASSWORD'] %>
